### PR TITLE
first stab at tag foldering

### PR DESCRIPTION
**Pull request by nkrabben**

### CODE REVIEW

**Comment by nkrabben** [comment]
@bturkus in response to tag file request

@genfhk is there a best place to put specs about what the tags directory holds?

**Comment by genfhk** [comment]
@nkrabben here? https://github.com/NYPL/ami-preservation/blob/master/docs/pages/ami-handling.md#digital-asset-packaging

**Comment by bturkus** [comment]
testing this out and finding a number of issues:

1. line 86: os module has no pwd function. switched to getcwd and seemed to be working
2. line 107 make objects was missing a parameter. added in source_directory and seemed to be working.

with these changes I got a directory structure that looks like this:

Screen Shot 2020-12-01 at 10 57 36 AM

but it was my understanding that tag files would not be checksummed, and in this case the timecode.txt was.

**Comment by nkrabben** [comment]
Not sure why the tag folder and tag manifest is going to the wrong place. I'll need to dummy up data.

**Comment by nkrabben** [comment]
Wow, very obvious mistake on my part, but should be working now.

**Comment by nkrabben** [comment]
Double check https://github.com/NYPL/ami-preservation/blob/5a172d14059a0deb7ee15652afc5ae553892994f/pami_scripts/split_projects_into_objects.py#L52

I'm filtering for anything that should be in the payload, so this should include the extensions for any file not considered a tag file.

**Review by bturkus — APPROVED** [review]
tested and lgtm

**Pull request merged**
